- .github/workflows/ci.yml
- examples/basic-example/deploy/001_deploy.ts
- examples/basic-example/deploy/002_factory.ts
- examples/basic-example/package.json
- packages/hardhat-zksync-deploy/package.json
- packages/hardhat-zksync-deploy/src/deployer.ts
- packages/hardhat-zksync-deploy/src/helpers.ts
- packages/hardhat-zksync-deploy/src/index.ts
- packages/hardhat-zksync-deploy/src/plugin.ts
- packages/hardhat-zksync-deploy/src/task-names.ts
- packages/hardhat-zksync-deploy/src/type-extensions.ts
- packages/hardhat-zksync-deploy/src/types.ts
- packages/hardhat-zksync-deploy/test/fixture-projects/successful-compilation/deploy/001_deploy.ts
- packages/hardhat-zksync-deploy/test/helpers.ts
- packages/hardhat-zksync-deploy/test/tests.ts
- packages/hardhat-zksync-solc/package.json
- packages/hardhat-zksync-solc/test/fixture-projects/factory/hardhat.config.js
- packages/hardhat-zksync-solc/test/fixture-projects/library/hardhat.config.js
- packages/hardhat-zksync-solc/test/fixture-projects/nested/hardhat.config.js
- packages/hardhat-zksync-solc/test/fixture-projects/successful-compilation/hardhat.config.js
- packages/hardhat-zksync-solc/test/helpers.ts
Adds CI for the `hardhat-zksync-solc` package.
For `hardhat-zksync-deploy` a local server setup is needed, so for now those tests are not run.
> Add CI & formatting

- packages/hardhat-zksync-deploy/package.json
- packages/hardhat-zksync-deploy/src/deployer.ts
- yarn.lock
> Remove fee tokens

- examples/basic-example/package.json
- packages/hardhat-zksync-deploy/package.json
- yarn.lock
Basically the title. No changes, just version bump.
Checked locally, seems to work.
> Bump versions for next release

- packages/hardhat-zksync-solc/package.json
- packages/hardhat-zksync-vyper/package.json
> Bump plugin versions

- packages/hardhat-zksync-deploy/package.json
- packages/hardhat-zksync-deploy/src/plugin.ts
- packages/hardhat-zksync-solc/src/utils.ts
- packages/hardhat-zksync-vyper/src/utils.ts
- yarn.lock
> Fix windows issues

- examples/basic-example/contracts/001_deploy/Greeter.sol
- examples/basic-example/contracts/003_account_abstraction/TwoUserMultisig.sol
- examples/basic-example/deploy/003_account_abstraction.ts
- examples/basic-example/package.json
- packages/hardhat-zksync-deploy/src/deployer.ts
- yarn.lock
> Support deploymentType in Deployer

- examples/verify-example/.eslintrc.js
- examples/verify-example/.gitignore
- examples/verify-example/README.md
- examples/verify-example/args.js
- examples/verify-example/contracts/Greeter.sol
- examples/verify-example/contracts/MintingContract.sol
- examples/verify-example/contracts/Test.sol
- examples/verify-example/contracts/interfaces/ITest.sol
- examples/verify-example/hardhat.config.ts
- examples/verify-example/package.json
- examples/verify-example/test/helpers.ts
- examples/verify-example/test/tests.ts
- examples/verify-example/tsconfig.json
- packages/hardhat-zksync-deploy/src/deployer.ts
- packages/hardhat-zksync-verify/src/constants.ts
- yarn.lock
*  hardhat-zksync-deploy and hardhat-zksync-verify changed to sepolia testnet
* Change from goerli testnet to sepolia testent network
> chore(sepolia-change): deploy and verify changed to sepolia testnet

- packages/hardhat-zksync-verify-vyper/src/constants.ts
- packages/hardhat-zksync-verify-vyper/test/common.config.ts
- packages/hardhat-zksync-verify-vyper/test/tests.ts
- yarn.lock
* changed goerli network to sepolia
> chore(hardhat-zksync-vyper-verify): changed goerli network to sepolia

- .changeset/polite-kings-relax.md
- examples/verify-example/hardhat.config.ts
- examples/verify-example/test/helpers.ts
- examples/verify-example/test/tests.ts
- packages/hardhat-zksync-verify/src/constants.ts
- packages/hardhat-zksync-verify/test/common.config.ts
- packages/hardhat-zksync-verify/test/tests.ts
Added support for Sepolia test-net.
Upcoming Goerli test-net deprecation.
> refactor(hardhat-zksync-verify):Add support for Sepolia testnet.

- packages/hardhat-zksync-chai-matchers/test/reverted/revertedWithPanic.ts
- packages/hardhat-zksync-toolbox/test/fixture-projects/simple/hardhat.config.ts
- packages/hardhat-zksync-toolbox/test/tests.ts
Updated verify url
Sepolia migrations
> chore(hardhat-zksync-toolbox): update verify url

- packages/hardhat-zksync-zksync2js/package.json
* First thing updated with this PR
* Second thing updated with this PR
* Third thing updated with this PR
* Reason why first thing was added to PR
* Reason why second thing was added to PR
* Reason why third thing was added to PR
> chore(hardhat-zksync-zksync2js): bumped version

- .changeset/cool-cheetahs-nail.md
- packages/hardhat-zksync-upgradable/package.json
- packages/hardhat-zksync-zksync2js/package.json
Bumped version of dependencies
> Nikola bozin txfusion upgradeable dependency versions bump

- .changeset/big-eagles-buy.md
- packages/hardhat-zksync-toolbox/package.json
Bumped version of dependenices
> chore(hardhat-zksync-toolbox): bump version of dependencies

- .changeset/five-oranges-perform.md
- packages/hardhat-zksync-deploy/package.json
Bump version
To trigger creating release after deps update
> fix(hardhat-zksync-deploy): Manually bump version of hardhat-zksync-deploy

- .changeset/wet-news-rhyme.md
- packages/hardhat-zksync-upgradable/package.json
> chore(hardhat-zksync-upgradable): add changeset

- .changeset/quick-chefs-marry.md
> chore(hardhat-zksync-chai-matchers): add changeset

- packages/hardhat-zksync-verify-vyper/package.json
> chore(hardhat-zksync-verify-vyper): version bump

- .github/workflows/ci.yml
- examples/upgradable-example/hardhat.config.ts
Updated CI file to work with zksync-ethers
> chore(github-workflow-ci): updated CI to work with zksync-ethers

- .changeset/honest-numbers-lie.md
- README.md
- packages/hardhat-zksync-deploy/package.json
- yarn.lock
> chore(hardhat-zksync-deploy): version bump

- .github/workflows/ci.yml
- package.json
- packages/hardhat-zksync-toolbox/package.json
- packages/hardhat-zksync-upgradable/package.json
- packages/hardhat-zksync-verify/package.json
- yarn.lock
Bumping version 
Migrating to zksync-ethers
> chore(hardhat-zksync-verify): bumping version for new realese

- .github/workflows/publish-chai-matchers.yml
- .github/workflows/publish-deploy.yml
- .github/workflows/publish-node.yaml
- .github/workflows/publish-toolbox.yml
- .github/workflows/publish-upgradable.yml
- .github/workflows/publish-verify.yml
- .github/workflows/publish-zkvyper-verify.yml
Removed mattermost job from publishing
For legacy ethers-v5
> chore(workflows/publish): removed mattermost job

- .github/workflows/ci.yml
- packages/hardhat-zksync-node/package.json
- packages/hardhat-zksync-node/test/tests.ts
Fixed tests for zksync ethers v5.
> fix(hardhat-zksync-node): updated tests

- README.md
- examples/README.md
- examples/basic-example/README.md
- examples/node-example/README.md
- examples/noninline-libraries-example/README.md
- examples/upgradable-example/README.md
- examples/verify-example/README.md
- examples/verify-vyper-example/README.md
- examples/vyper-example/README.md
- examples/zksync-ethers-example/README.md
- packages/hardhat-zksync-chai-matchers/README.md
- packages/hardhat-zksync-deploy/README.md
- packages/hardhat-zksync-ethers/README.md
- packages/hardhat-zksync-node/README.md
- packages/hardhat-zksync-solc/README.md
- packages/hardhat-zksync-toolbox/README.md
- packages/hardhat-zksync-upgradable/README.md
- packages/hardhat-zksync-verify-vyper/README.md
- packages/hardhat-zksync-verify/README.md
- packages/hardhat-zksync-vyper/README.md
Updating readme documentation.
For better developer experience.
> docs(readme): Update packages readme files 

- README.md
- examples/basic-example/README.md
- examples/node-example/README.md
- examples/noninline-libraries-example/README.md
- examples/upgradable-example/README.md
- examples/verify-example/README.md
- examples/verify-vyper-example/README.md
- examples/vyper-example/README.md
- examples/zksync-ethers-example/README.md
- packages/hardhat-zksync-chai-matchers/README.md
- packages/hardhat-zksync-deploy/README.md
- packages/hardhat-zksync-ethers/README.md
- packages/hardhat-zksync-node/README.md
- packages/hardhat-zksync-solc/README.md
- packages/hardhat-zksync-toolbox/README.md
- packages/hardhat-zksync-upgradable/README.md
- packages/hardhat-zksync-verify-vyper/README.md
- packages/hardhat-zksync-verify/README.md
- packages/hardhat-zksync-vyper/README.md
Update README files.
For better developer's experience.
> fix(docs): update readme files

- .github/workflows/npm-publish.yaml
Exclude mattermost from npm publish
> chore: mattermost exclude from npm publish

- packages/hardhat-zksync-ethers/package.json
* hardhat-zksync-ethers bump version
* For better developer's experience
> update: hardhat-zksync-ethers bump version

- packages/hardhat-zksync-verify-vyper/package.json
* hardhat-zksync-verify-vyper bump version
* For better developer's experience
> update: hardhat-zksync-verify-vyper bump version

- .github/workflows/check-pr-title.yml
Add workflow for pr title check
Ensure clarity and relevance of changes for project tracking
> chore: add workflow for pr title check

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/config.yaml
* First thing updated with this PR
* Second thing updated with this PR
* Third thing updated with this PR
* Reason why first thing was added to PR
* Reason why second thing was added to PR
* Reason why third thing was added to PR
> chore: fix dev discussions link

- packages/hardhat-zksync-verify/src/config-extractor.ts
- packages/hardhat-zksync-verify/src/config-normalizer.ts
- packages/hardhat-zksync-verify/src/constants.ts
- packages/hardhat-zksync-verify/src/task-actions.ts
- packages/hardhat-zksync-verify/src/type-extensions.ts
- packages/hardhat-zksync-verify/src/utils.ts
- packages/hardhat-zksync-verify/test/tests/config-extractor.test.ts
- packages/hardhat-zksync-verify/test/tests/config-normalizer.test.ts
- packages/hardhat-zksync-verify/test/tests/task-actions.test.ts
- packages/hardhat-zksync-verify/test/tests/utils.test.ts
* Support for zkvm solc compiler verification
* hardhat-zksync-solc support zkvm compilers and verify must be able to support this compiler in verification process.
> feat: support for zkvm solc compiler verification

- packages/hardhat-zksync-deploy/package.json
* No timeout for deploy tests
* Some of tests need a lot of time, so we need to avoid test fails
> chore: no timeout for deploy tests

- packages/hardhat-zksync-solc/README.md
- packages/hardhat-zksync-vyper/README.md
*Move fallbaclOz to optimize section and update readme files
> chore: move fallbaclOz to optimize section

- packages/hardhat-zksync-vyper/.eslintrc.js
- packages/hardhat-zksync-vyper/README.md
- packages/hardhat-zksync-vyper/src/compile/binary.ts
- packages/hardhat-zksync-vyper/src/compile/index.ts
- packages/hardhat-zksync-vyper/src/constants.ts
- packages/hardhat-zksync-vyper/src/types.ts
- packages/hardhat-zksync-vyper/test/fixture-projects/simple-fallback/contracts/Greeter.vy
- packages/hardhat-zksync-vyper/test/fixture-projects/simple-fallback/hardhat.config.ts
- packages/hardhat-zksync-vyper/test/tests.ts
* Support an option to fallback to optimizing for size vyper
* From 1.3.15 zkvyper support this optimization and plugin needs to support this flag as well
> feat: support an option to fallback to optimizing for size vyper

- .github/release-please/config.json
- .github/release-please/manifest.json
- .github/workflows/ci.yml
- examples/verify-example/hardhat.config.ts
- examples/zksync-ethers-example/deploy/001_deploy.ts
- examples/zksync-ethers-example/hardhat.config.ts
- packages/hardhat-zksync-ethers/src/constants.ts
- packages/hardhat-zksync-ethers/src/helpers.ts
- packages/hardhat-zksync-ethers/src/index.ts
- packages/hardhat-zksync-ethers/src/type-extensions.ts
- packages/hardhat-zksync-ethers/src/types.ts
- packages/hardhat-zksync-ethers/src/utils.ts
- packages/hardhat-zksync-ethers/test/fixture-projects/simple-accounts/hardhat.config.ts
- packages/hardhat-zksync-ethers/test/fixture-projects/simple/hardhat.config.ts
- packages/hardhat-zksync-ethers/test/tests.ts
- yarn.lock
* L1 provider support in ethers plugin
* Need L1 provider to be used in the taska,scripts..
> feat: L1 provider support in ethers plugin

- examples/verify-vyper-example/test/tests.ts
* Fixed a spelling error in the code comments.
* Corrected the spelling error to improve code readability and accuracy.
N/A
* No special notes or challenges for this change.
> chore: fix typo in test case description

- packages/hardhat-zksync-chai-matchers/package.json
- packages/hardhat-zksync-chai-matchers/src/constants.ts
- packages/hardhat-zksync-chai-matchers/src/errors.ts
- packages/hardhat-zksync-chai-matchers/src/internal/changeEtherBalance.ts
- packages/hardhat-zksync-chai-matchers/src/internal/changeEtherBalances.ts
- packages/hardhat-zksync-chai-matchers/src/internal/changeTokenBalance.ts
- packages/hardhat-zksync-chai-matchers/src/internal/hardhatChaiMatchers.ts
- packages/hardhat-zksync-chai-matchers/src/internal/reverted/reverted.ts
- packages/hardhat-zksync-chai-matchers/src/internal/reverted/revertedWith.ts
- packages/hardhat-zksync-chai-matchers/src/internal/reverted/revertedWithCustomError.ts
- packages/hardhat-zksync-chai-matchers/src/internal/reverted/revertedWithPanic.ts
- packages/hardhat-zksync-chai-matchers/src/internal/reverted/revertedWithoutReason.ts
- packages/hardhat-zksync-chai-matchers/src/internal/utils.ts
- packages/hardhat-zksync-chai-matchers/test/changeEtherBalance.ts
- packages/hardhat-zksync-chai-matchers/test/changeEtherBalances.ts
- packages/hardhat-zksync-chai-matchers/test/changeTokenBalance.ts
- packages/hardhat-zksync-chai-matchers/test/helpers.ts
- packages/hardhat-zksync-chai-matchers/test/reverted/misc.ts
- packages/hardhat-zksync-chai-matchers/test/reverted/reverted.ts
- packages/hardhat-zksync-chai-matchers/test/reverted/revertedWith.ts
- packages/hardhat-zksync-chai-matchers/test/reverted/revertedWithPanic.ts
- packages/hardhat-zksync-chai-matchers/test/types.ts
- yarn.lock
Added regular expression support.
In order to extend testing capabilities of the plugin.
> fix: add regex support

- packages/hardhat-zksync-toolbox/package.json
Dependencies version bump
In order to have latest versions of toolbox dependencies.
> feat: dependencies version bump

- packages/hardhat-zksync-chai-matchers/CHANGELOG.md
* remove unnecessary chai matchers change log
> chore: remove unnecessary chai matchers change log

- packages/hardhat-zksync-toolbox/package.json
- yarn.lock
Dependencies version bump
In order to have latest versions of toolbox dependencies.
> fix: bump dependency versions

- packages/hardhat-zksync-deploy/README.md
* small grammarly fix in the readme file
> chore: small grammarly fix in the readme file

- .github/release-please/manifest.json
- packages/hardhat-zksync-chai-matchers/test/fixture-projects/hardhat-project/hardhat.config.ts
- packages/hardhat-zksync-deploy/CHANGELOG.md
- packages/hardhat-zksync-deploy/package.json
* revert release @matterlabs/hardhat-zksync-deploy 1.2.0
> chore: revert release @matterlabs/hardhat-zksync-deploy 1.2.0

- packages/hardhat-zksync-chai-matchers/package.json
- packages/hardhat-zksync-chai-matchers/test/fixture-projects/hardhat-project/hardhat.config.ts
- yarn.lock
* bump dependecies to newer versions
* Bump versions of hardhat-zksync-solc and hardhat-zksync-deploy to the newest
> feat: bump dependecies to newer versions

- .github/release-please/manifest.json
- packages/hardhat-zksync-solc/CHANGELOG.md
- packages/hardhat-zksync-solc/package.json
Reverts matter-labs/hardhat-zksync#827
> chore(main): revert release @matterlabs/hardhat-zksync-solc 1.1.4

- examples/deploy-example/deploy/003_deploy.ts
- examples/deploy-example/tsconfig.json
- examples/upgradable-example/scripts/deploy-box-beacon.ts
- examples/upgradable-example/scripts/deploy-box-proxy.ts
- examples/upgradable-example/scripts/deploy-box-uups.ts
- examples/upgradable-example/scripts/upgrade-box-beacon.ts
- examples/upgradable-example/scripts/upgrade-box-uups.ts
- examples/upgradable-example/scripts/upgrade-box.ts
- packages/hardhat-zksync-chai-matchers/test/reverted/revertedWithPanic.ts
- packages/hardhat-zksync-deploy/src/deployer-extension.ts
- packages/hardhat-zksync-node/src/downloader.ts
- packages/hardhat-zksync-verify/src/task-actions.ts
* Run lint formatter at whole project
> chore: run lint formatter

- .husky/pre-commit
- package.json
- yarn.lock
* Add husky with pre-commit lint
> chore: add husky with pre-commit lint

- packages/hardhat-zksync-verify/package.json
- packages/hardhat-zksync-verify/src/task-actions.ts
- packages/hardhat-zksync-verify/src/utils.ts
Removed unnecessary dependency from the package.
The dependency is unnecessary, and its removal can reduce maintenance costs.
> fix: remove zksync-ethers dependency

- examples/deploy-example/deploy/003_deploy.ts
- examples/verify-example/contracts/Box.sol
- examples/verify-example/contracts/BoxUups.sol
- examples/verify-example/contracts/BoxUupsV2.sol
- examples/verify-example/contracts/BoxV2.sol
- examples/verify-example/contracts/Empty.sol
- examples/verify-example/contracts/Factory.sol
- examples/verify-example/contracts/FactoryUups.sol
- examples/verify-example/contracts/FactoryUupsV2.sol
- examples/verify-example/contracts/FactoryV2.sol
- examples/verify-example/hardhat.config.ts
- examples/verify-example/test/helpers.ts
- examples/verify-example/test/upgradables.ts
- yarn.lock
Add upgradable smart contracts verification example.
In order to ensure proper functionallity between hardhat-zskync-verify and hardhat-zksync-upgradable plugins.
> chore: add upgradable contracts verification

- packages/hardhat-zksync-verify-vyper/src/utils.ts
- packages/hardhat-zksync-verify/src/utils.ts
Applied lint to verification packages.
> chore: lint verify packages

- packages/hardhat-zksync-verify/test/tests/plugin.test.ts
- packages/hardhat-zksync-verify/test/tests/task-actions.test.ts
- packages/hardhat-zksync-verify/test/tests/utils.test.ts
- packages/hardhat-zksync-verify/test/tests/zksync-block-explorer/service.test.ts
Bump hardhat-zksync-verify test coverage
Include additional unit tests and functionalities in order to make sure proper functioning of the plugin.
> chore: bump test coverage

- e2e/fixture-projects/node/preprocess.sh
- e2e/fixture-projects/node/test.sh
- e2e/fixture-projects/upgradeable/preprocess.sh
- e2e/fixture-projects/upgradeable/test.sh
- e2e/run-fixture-projects.sh
Properly installing dependencies in temporary directory.
To avoid lock file conflicts.
> chore: properly install dependencies

- .github/workflows/npm-publish.yaml
> chore: update npm-publish to install with pnpm

- .github/workflows/npm-publish.yaml
* Update npm-publish to publish  with pnpm
> chore: update npm-publish to publish  with pnpm

- packages/hardhat-zksync-chai-matchers/package.json
- packages/hardhat-zksync-ethers/package.json
- packages/hardhat-zksync-upgradable/package.json
- pnpm-lock.yaml
* Bump hardhat-zksync-deploy dependency version
* Update hardhat-zksync-deploy version in other packages to use newest version
> feat: bump hardhat-zksync-deploy and hardhat-zksync-solc dependency version

- packages/hardhat-zksync-verify/test/tests/plugin.test.ts
- packages/hardhat-zksync-verify/test/tests/solc/bytecode.test.ts
- packages/hardhat-zksync-verify/test/tests/task-actions.test.ts
Add additional tests
In order to test additional functionalities and increase coverage.
> chore: increase test coverage

- .github/workflows/ci.yml
- e2e/fixture-projects/compatability-check/hardhat.config.ts
- e2e/fixture-projects/mixed/hardhat.config.ts
- e2e/fixture-projects/mixed/scripts/deploy-box-proxy.ts
- e2e/fixture-projects/mixed/scripts/deploy-greeter.ts
- e2e/fixture-projects/mixed/scripts/upgrade-box.ts
- e2e/fixture-projects/node/hardhat.config.ts
- e2e/fixture-projects/upgradeable/hardhat.config.ts
- examples/basic-example/hardhat.config.ts
- examples/mixed-example/hardhat.config.ts
- examples/upgradable-example/hardhat.config.ts
- examples/vyper-example/hardhat.config.ts
- examples/zksync-ethers-example/hardhat.config.ts
- packages/hardhat-zksync-deploy/src/constants.ts
- packages/hardhat-zksync-deploy/test/fixture-projects/plugin-functionalities/hardhat.config.ts
- packages/hardhat-zksync-deploy/test/tests/deployer-helper.test.ts
- packages/hardhat-zksync-deploy/test/tests/tests.ts
- packages/hardhat-zksync-ethers/src/constants.ts
- packages/hardhat-zksync-ethers/test/fixture-projects/simple-accounts/hardhat.config.ts
- packages/hardhat-zksync-ethers/test/fixture-projects/simple/hardhat.config.ts
- packages/hardhat-zksync-ethers/test/tests.ts
- packages/hardhat-zksync-solc/test/tests/utils.test.ts
- packages/hardhat-zksync-upgradable/src/constants.ts
- packages/hardhat-zksync-upgradable/test/tests.ts
Updated hardhat config's of packages and examples to work with proper network url's.
In order to stabilize the CI workflow and ensure tests pass correctly.
> chore: update hardhat.config to work with proper network url's

- packages/hardhat-zksync-upgradable/README.md
- packages/hardhat-zksync-upgradable/src/index.ts
- packages/hardhat-zksync-upgradable/src/plugin.ts
- packages/hardhat-zksync-upgradable/src/proxy-deployment/deploy-beacon-proxy.ts
- packages/hardhat-zksync-upgradable/src/proxy-deployment/deploy-impl.ts
- packages/hardhat-zksync-upgradable/src/proxy-deployment/deploy-proxy.ts
- packages/hardhat-zksync-upgradable/src/utils/options.ts
*  Extend deploy and upgrade of proxy with deployment type and salt
* To support different deployment types and salts.
> fix: extend deploy and upgrade of proxy with deployment type and salt

- e2e/fixture-projects/clean/preprocess.sh
- e2e/fixture-projects/compile-fail/preprocess.sh
- e2e/fixture-projects/node/preprocess.sh
- e2e/fixture-projects/upgradeable/preprocess.sh
- packages/hardhat-zksync-chai-matchers/package.json
- packages/hardhat-zksync-deploy/package.json
- packages/hardhat-zksync-deploy/test/tests/deployer-helper.test.ts
- packages/hardhat-zksync-ethers/package.json
- packages/hardhat-zksync-node/package.json
- packages/hardhat-zksync-upgradable/package.json
- packages/hardhat-zksync-verify-vyper/package.json
- packages/hardhat-zksync-verify/package.json
- packages/hardhat-zksync/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
* Resolve local dependencies as workspace:^
* To avoid build problems when releasing a new versions
> chore: resolve local dependencies as workspace

- .github/workflows/ci.yml
- .github/workflows/npm-publish.yaml
* Use packageManager from the package.json in the workflow scripts
> chore: use package manager from the package.json in the workflow

- e2e/fixture-projects/compatability-check/scripts/deploy-factory-uups.ts
- examples/upgradable-example/README.md
- examples/verify-example/test/tests.ts
- examples/verify-example/test/upgradables.ts
- examples/verify-vyper-example/test/tests.ts
* Updated console log message in `deploy-factory-uups.ts`
* Corrected a typo in the README file of `upgradable-example`
* Fixed typos and grammatical errors in test descriptions in `tests.ts` files
* The console log message was updated for clarity and correctness.
* The typo in the README file was corrected to improve readability.
* Typos and grammatical errors in test descriptions were fixed to enhance clarity and maintain consistency.
These changes are minor and do not affect the code's compilation.
> fix: Minor typos and enhance clarity in console log messages and documentation

- packages/hardhat-zksync-verify/package.json
- pnpm-lock.yaml
* Resolve hardhat dependency  as dev dependency.
* Hardhat should be listed as a dev dependency.
> fix: move hardhat dependency to dev dependencies

- packages/hardhat-zksync-node/package.json
- pnpm-lock.yaml
* Delete unused zksync-ethers dependency
> chore: delete unused dependency

- .github/dependabot.yml
* Resolve dependabot.yaml error
> chore: resolve dependabot.yaml error

- .github/workflows/github-release.yml
* Add beta branches to the github release please
> chore: add beta branches to the github release please

- examples/zksync-ethers-example/deploy/001_deploy.ts
- examples/zksync-ethers-example/deploy/002_deploy.ts
- packages/hardhat-zksync-ethers/src/extension-generator.ts
Update zksync-ethers import syntax in order to have properly imported components.
> fix: update zksync-ethers import syntax

- examples/zksync-ethers-example/deploy/001_deploy.ts
- examples/zksync-ethers-example/deploy/002_deploy.ts
- packages/hardhat-zksync-ethers/src/extension-generator.ts
Update zksync-ethers import syntax in order to have properly imported components.
> fix: update zksync-ethers import syntax v5

- .github/release-please/manifest.json
- packages/hardhat-zksync-solc/CHANGELOG.md
- packages/hardhat-zksync-solc/package.json
Reverts matter-labs/hardhat-zksync#1444
> Revert "chore(main): release @matterlabs/hardhat-zksync-solc 1.2.5"

- packages/hardhat-zksync-upgradable/src/proxy-deployment/deploy-beacon.ts
* Provide paymaster params for the beacon deployment
> fix: provide paymaster params for the beacon deployment

- packages/hardhat-zksync-upgradable/src/proxy-upgrade/upgrade-beacon.ts
- packages/hardhat-zksync-upgradable/src/proxy-upgrade/upgrade-proxy.ts
* Add paymaster support for implementation upgrade
> fix: add paymaster support for implementation upgrade

- packages/hardhat-zksync-node/src/downloader.ts
- packages/hardhat-zksync-node/src/utils.ts
* Create node cache directory with permissions
> fix: create node cache directory with permissions

- packages/hardhat-zksync-node/src/index.ts
* Add type extension to the index
> fix: add type extension to the index

- packages/hardhat-zksync-telemetry/package.json
- pnpm-lock.yaml
- update telemetry lib
- updated lib fixes installation issues
> fix: update telemetry-js lib

- packages/hardhat-zksync-node/src/constants.ts
* Updates the default anvil-zksync tag
* Was using a very outdated version 
> fix: bump anvil-zksync default version

- packages/hardhat-zksync/test/fixture-projects/simple/hardhat.config.ts
* This empty PR is used to trigger the release process. It includes no code changes but will be used to bump all plugin versions and publish the updated packages.
> feat: bump all plugin versions

- packages/hardhat-zksync-verify/src/solc/bytecode.ts
- packages/hardhat-zksync-verify/test/tests/task-actions.test.ts
* Compare proper bytecode execution part lengths in the verification process.
> fix: compare proper bytecode execution parts

- .github/workflows/ci.yml
- .husky/pre-commit
- e2e/fixture-projects/clean/hardhat.config.ts
- e2e/fixture-projects/clean/preprocess.sh
- e2e/fixture-projects/compatability-check/hardhat.config.ts
- e2e/fixture-projects/compile-fail/hardhat.config.ts
- e2e/fixture-projects/compile-fail/preprocess.sh
- e2e/fixture-projects/mixed/contracts/Box.sol
- e2e/fixture-projects/mixed/contracts/BoxV2.sol
- e2e/fixture-projects/mixed/hardhat.config.ts
- e2e/fixture-projects/mixed/preprocess.sh
- e2e/fixture-projects/node/hardhat.config.ts
- e2e/fixture-projects/upgradeable/hardhat.config.ts
- e2e/fixture-projects/upgradeable/preprocess.sh
- e2e/fixture-projects/upgradeable/test.sh
- examples/basic-example/hardhat.config.ts
- packages/hardhat-zksync-solc/src/compile/downloader.ts
- packages/hardhat-zksync-solc/src/index.ts
- packages/hardhat-zksync-solc/src/utils.ts
- packages/hardhat-zksync-solc/test/tests/compile/downloader.test.ts
- packages/hardhat-zksync-upgradable/test/fixture-projects/admin/hardhat.config.ts
- packages/hardhat-zksync-upgradable/test/fixture-projects/beacon-e2e/hardhat.config.ts
- packages/hardhat-zksync-upgradable/test/fixture-projects/deployment-gas-estimation/hardhat.config.ts
- packages/hardhat-zksync-upgradable/test/fixture-projects/storage-layout-validations/contracts/BoxWithStorageGap.sol
- packages/hardhat-zksync-upgradable/test/fixture-projects/storage-layout-validations/contracts/BoxWithStorageGapV2.sol
- packages/hardhat-zksync-upgradable/test/fixture-projects/storage-layout-validations/contracts/BoxWithStorageGapV2Invalid.sol
- packages/hardhat-zksync-upgradable/test/fixture-projects/storage-layout-validations/hardhat.config.ts
- packages/hardhat-zksync-upgradable/test/fixture-projects/tup-e2e/hardhat.config.ts
- packages/hardhat-zksync-upgradable/test/fixture-projects/uups-e2e/hardhat.config.ts
- packages/hardhat-zksync-upgradable/test/tests.ts
* Remove latest version leftovers
* Fix e2e tests
> fix: remove latest version leftovers

- packages/hardhat-zksync/test/fixture-projects/simple/hardhat.config.ts
* use 1.5.15 zksolc
* add settings
* use intentional version
> chore: bump zksolc version and add required settings
