matter-labs/hardhat-zksync

packages/hardhat-zksync-solc/package.json
packages/hardhat-zksync-solc/src/index.ts

Downloading missing versions of `solc` is unnecessary, since
- if compiler source is `binary`, `solc` is taken from `$PATH`
- if compiler source if `docker`, `solc` is inside of the container
And the only version supported is the latest one (0.8.11 currently) anyway.

Don't download solc

---

packages/hardhat-zksync-deploy/package.json
packages/hardhat-zksync-deploy/src/deployer.ts
yarn.lock

Goerli is now the default L1 testnet. Bumped zksync-web3, otherwise all deploys would fail since 0.2 is missing the chainId tx serialization
Not sure how you guys prefer to do npm releases, so I left the package version as is

add goerli and bump zksync-web3 version

---

packages/hardhat-zksync-solc/src/index.ts

A bug was introduced in bd06d2447b296546c1940c18453313d344216af7, where hardhat would always recompile because the solc cache entry differed from the input solc. One would have `libraries: {}` and the other would not include that setting.
This was due to adding `libraries: {}` to the default config and then later checking:
```
if (config.zksolc.settings.libraries) {
input.settings.libraries = config.zksolc.settings.libraries;
}
```
Which will always evaluate to true and updates the input settings. I removed libraries from the default config but another option is to just change to check that the object has keys in the above if statement instead of checking that it exists.

Fix library default config bug

---

.gitignore
packages/hardhat-zksync-solc/src/index.ts
packages/hardhat-zksync-solc/src/type-extensions.ts
packages/hardhat-zksync-solc/test/fixture-projects/factory/hardhat.config.js
packages/hardhat-zksync-solc/test/fixture-projects/library/hardhat.config.js
packages/hardhat-zksync-solc/test/fixture-projects/linked/hardhat.config.js
packages/hardhat-zksync-solc/test/fixture-projects/nested/hardhat.config.js
packages/hardhat-zksync-solc/test/fixture-projects/simple/hardhat.config.js
packages/hardhat-zksync-solc/test/helpers.ts

One point of feedback that keeps coming up from devs is not having the ability to compile using standard solidity and zksolc within a project. This PR adds the logic so that both solc and zksolc tasks can run and the artifacts are stored separately. Optimism uses similar logic so it follows a set standard of having `artifacts-zk` & `cache-zk` paths.
A `zksync` network boolean is added and if it is true it loads the full zksolc compiler config. That way users can separate how they want to compile by network without changing anything

Allow both solc and zksolc compilers

---

packages/hardhat-zksync-solc/package.json
packages/hardhat-zksync-solc/src/compile/binary.ts
packages/hardhat-zksync-solc/src/compile/index.ts
packages/hardhat-zksync-solc/src/index.ts
packages/hardhat-zksync-solc/src/type-extensions.ts
packages/hardhat-zksync-solc/src/types.ts

- makes path to `zksolc` configurable and does not rely on it being in `$PATH`
- makes use of `solc` provided/downloaded by hardhat (instead of the one in `$PATH`)
- enforces `solc` version to be compatible with `zksolc`

Make zksolc path configurable 

---

examples/basic-example/hardhat.config.ts
packages/hardhat-zksync-deploy/package.json
packages/hardhat-zksync-solc/package.json
packages/hardhat-zksync-solc/src/compile/docker.ts
packages/hardhat-zksync-solc/src/compile/index.ts
packages/hardhat-zksync-solc/src/index.ts
packages/hardhat-zksync-solc/src/types.ts
packages/hardhat-zksync-solc/test/fixture-projects/factory/hardhat.config.js
packages/hardhat-zksync-solc/test/fixture-projects/library/hardhat.config.js
packages/hardhat-zksync-solc/test/fixture-projects/linked/hardhat.config.js
packages/hardhat-zksync-solc/test/fixture-projects/nested/hardhat.config.js
packages/hardhat-zksync-solc/test/fixture-projects/simple/hardhat.config.js

- fixes #88 
- switch example config from js to ts
- only log the deprecation warning once even if there are multiple compile jobs
- includes changes from #77

Fix multiple issues

---

examples/basic-example/hardhat.config.ts
packages/hardhat-zksync-solc/package.json
packages/hardhat-zksync-solc/src/compile/docker.ts
packages/hardhat-zksync-solc/src/compile/index.ts
packages/hardhat-zksync-solc/src/index.ts
packages/hardhat-zksync-vyper/package.json
yarn.lock

Note that it's not in the actual contracts' artifacts, but rather in the build-info files and cache.

Add the actual solc version to the artifacts when using docker

---

packages/hardhat-zksync-solc/package.json
packages/hardhat-zksync-solc/src/index.ts
yarn.lock

Turns out that if we try to save the correct `solcVersion` to `build-info` and `cache` when using docker, it results in a permanently invalid cache, since we change the `solcVersion` after checking the cache and before saving it. Since we can only get it after the compilation (from the artifacts), there is no way to prevent it.
Invalid cache means recompiling everything every time, which is suboptimal and results in a terrible UX.
Hence, the solution, unfortunately, is to save an invalid `solcVersion` when using docker (alongside the valid ones - `output.version`, `output.long_version` and `output.zk_version` which should be used if needed).
Still, when using binary `zksolc` releases, everything should work smoothly.

Fix cache invalidation

---

.github/workflows/ci.yml
examples/basic-example/deploy/001_deploy.js
examples/basic-example/deploy/002_factory.ts
examples/basic-example/hardhat.config.ts
examples/vyper-example/deploy/deploy.ts
examples/vyper-example/hardhat.config.ts
packages/hardhat-zksync-solc/test/common.config.ts
packages/hardhat-zksync-solc/test/fixture-projects/factory/contracts/Factory.sol
packages/hardhat-zksync-solc/test/fixture-projects/library/contracts/Foo.sol
packages/hardhat-zksync-solc/test/fixture-projects/library/contracts/Import.sol
packages/hardhat-zksync-solc/test/fixture-projects/linked/contracts/Foo.sol
packages/hardhat-zksync-solc/test/fixture-projects/linked/contracts/Import.sol
packages/hardhat-zksync-solc/test/fixture-projects/linked/hardhat.config.js
packages/hardhat-zksync-solc/test/fixture-projects/nested/contracts/NestedFactory.sol
packages/hardhat-zksync-solc/test/fixture-projects/nested/contracts/deps/Foo.sol
packages/hardhat-zksync-solc/test/fixture-projects/nested/contracts/deps/more_deps/Bar.sol
packages/hardhat-zksync-solc/test/fixture-projects/simple/contracts/Greeter.sol
packages/hardhat-zksync-solc/test/tests.ts
packages/hardhat-zksync-vyper/test/tests.ts

- Tests for `hardhat-zksync-solc` on both MacOS and Ubuntu, paired with `solc` v0.4 / v0.7 / v0.8.
- Tests for `hardhat-zksync-deploy` using this repo's examples and the [local-setup](https://github.com/matter-labs/local-setup) node.
- Some extra tests for `hardhat-zksync-vyper`.

Implement integration testing and extend test coverage

---

packages/hardhat-zksync-solc/package.json
packages/hardhat-zksync-solc/src/constants.ts
packages/hardhat-zksync-solc/src/index.ts
packages/hardhat-zksync-solc/src/utils.ts

Besides exporting some needed items, it is also ensured that the compiler is not re-downloaded when not needed

export some items from hardhat-zksync-solc

---

.changeset/orange-years-sip.md
packages/hardhat-zksync-verify/package.json
packages/hardhat-zksync-verify/src/index.ts
packages/hardhat-zksync-verify/src/task-actions.ts
packages/hardhat-zksync-verify/src/types.ts

This adds `noCompile` flag to the contract verification script to not recompile the contracts before sending verification request.
Made similar as in etherscan: https://github.com/NomicFoundation/hardhat/pull/3372
Also moved: `@nomicfoundation/hardhat-verify` from devDependencies to dependencies, because it is used in production build as well and causes a runtime error.

fix: add no compile flag to hardhat verify

---

.changeset/gentle-tools-press.md
packages/hardhat-zksync-solc/src/compile/downloader.ts
packages/hardhat-zksync-solc/src/constants.ts
packages/hardhat-zksync-solc/src/utils.ts

* Latest compiler info we fetch from latest release and min version we get from plugin.
* We don't want to use the version.json file from zksolc-bin repo.

chore(hardhat-zksync-solc): update solc compiler info file from release

---

.changeset/real-cooks-end.md
examples/basic-example/package.json
examples/mixed-example/package.json
examples/node-example/package.json
examples/noninline-libraries-example/package.json
examples/verify-example/package.json
examples/vyper-example/package.json
examples/zksync2js-example/package.json
packages/hardhat-zksync-chai-matchers/package.json
packages/hardhat-zksync-deploy/package.json
packages/hardhat-zksync-deploy/src/deployer.ts
packages/hardhat-zksync-deploy/src/plugin.ts
packages/hardhat-zksync-node/package.json
packages/hardhat-zksync-toolbox/package.json
packages/hardhat-zksync-verify-vyper/package.json
packages/hardhat-zksync-verify/package.json
packages/hardhat-zksync-zksync2js/package.json
yarn.lock

Bumped version for zksync2-js and added support for Sepolia test-net.
Goerli test-net incoming deprecation.

refactor(hardhat-zksync-deploy): Add support for Sepolia testnet

---

.changeset/sour-dancers-tie.md
packages/hardhat-zksync-node/src/constants.ts
packages/hardhat-zksync-node/src/downloader.ts

Fixes param for `getRelease` func, now it will be real User-Agent.
Requesting server with wrong User-Agent may be resulted in rate-limiting, random 403 errs, and so on.
It was broken (and still worked, since having proper UA not a must 😅 ) with name of plugin used as User-Agent, so no bad will happen if we will use proper UA.

fix(hardhat-zksync-node): Proper user_agent for getRelease

---

.changeset/ten-foxes-approve.md
packages/hardhat-zksync-solc/src/compile/downloader.ts
packages/hardhat-zksync-solc/src/utils.ts
yarn.lock

* Get latest release from redirect URL
* When fetching releases from GH api it can throttle and thus break the flow

chore(hardhat-zksync-solc): get latest release from redirect URL

---

.github/CONTRIBUTING.md

I've found broken link to developer discussion, this PR fixes the link. Maybe the target [repo](https://github.com/zkSync-Community-Hub/zkync-developers/discussions) should be renamed because the repo name contains a typo.
- Keep external resources approachable.
No additional evidence.

fix: update link to dev discussion

---

packages/hardhat-zksync-vyper/package.json
packages/hardhat-zksync-vyper/src/compile/index.ts
packages/hardhat-zksync-vyper/src/constants.ts
packages/hardhat-zksync-vyper/test/tests.ts

* Windows path normalize with compiler
* From compiler version 1.3.16 windows path are resolved and plugin don't need to do that.

fix: windows path normalize with compiler

---

.github/CODEOWNERS

* add CODEOWNERS for the repo
* Add organization that is responsible for external PRs

chore: add codeowners for the repo

---

packages/hardhat-zksync-solc/src/compile/binary.ts
packages/hardhat-zksync-solc/src/compile/docker.ts
packages/hardhat-zksync-solc/src/compile/index.ts
packages/hardhat-zksync-solc/src/constants.ts
packages/hardhat-zksync-solc/src/types.ts
packages/hardhat-zksync-solc/test/compiler-files/macos/solc-macos:Zone.Identifier
packages/hardhat-zksync-solc/test/compiler-files/macos/zksolc-macosx-arm64-v1.3.17:Zone.Identifier
packages/hardhat-zksync-solc/test/tests/compile/index.test.ts

* Support an option to fallback to optimizing for size if bytecode is too large
* From `1.3.21` zksolc support this optimization and plugin needs to support this flag as well

feat: support an option to fallback to optimizing for size solc

---

packages/hardhat-zksync-chai-matchers/tsconfig.json
packages/hardhat-zksync-solc/src/compile/binary.ts
packages/hardhat-zksync-solc/src/compile/docker.ts
packages/hardhat-zksync-solc/src/compile/index.ts
packages/hardhat-zksync-solc/src/types.ts
packages/hardhat-zksync-solc/test/tests/compile/index.test.ts

* Move fallback optimizing for size to optimizer section
* Guard for standard JSON is introduced which blocks --fallbackOz flag in zksolc compiler

fix: move fallback optimizing for size to optimizer section

---

packages/hardhat-zksync-upgradable/src/core/provider.ts

Added support for Sepolia and zkSync Era Test node
For proper folder naming when deploying upgradable contracts.

fix: add support for sepolia and zksync era test node

---

packages/hardhat-zksync-upgradable/src/verify/verify-beacon.ts
packages/hardhat-zksync-upgradable/src/verify/verify-proxy.ts
packages/hardhat-zksync-upgradable/src/verify/verify-transparent-uups.ts

* Add no compile flag propagation for ethers-v5
* To support older verification of contracts compiled with currently unsupported zksolc versions.

fix: add no compile flag propagation for ethers-v5

---

packages/hardhat-zksync-node/src/constants.ts
packages/hardhat-zksync-node/src/downloader.ts
packages/hardhat-zksync-node/src/utils.ts
packages/hardhat-zksync-node/test/tests.ts

* Get release tag from redirect url at node plugin
* To avoid throttling from github

feat: get release tag from redirect url at node plugin

---

packages/hardhat-zksync-node/src/constants.ts
packages/hardhat-zksync-node/src/downloader.ts
packages/hardhat-zksync-node/src/utils.ts
packages/hardhat-zksync-node/test/tests.ts

* Get release tag from redirect url at node plugin
* To avoid throttling from github

fix: get release tag from redirect url at node plugin

---

.github/workflows/ci.yml
examples/upgradable-example/contracts/Empty.sol
examples/upgradable-example/contracts/Factory.sol
examples/upgradable-example/contracts/FactoryUups.sol
examples/upgradable-example/contracts/FactoryUupsV2.sol
examples/upgradable-example/contracts/FactoryV2.sol
examples/upgradable-example/scripts/deploy-factory-beacon.ts
examples/upgradable-example/scripts/deploy-factory-proxy.ts
examples/upgradable-example/scripts/deploy-factory-uups.ts
examples/upgradable-example/scripts/upgrade-box-beacon.ts
examples/upgradable-example/scripts/upgrade-factory-beacon.ts
examples/upgradable-example/scripts/upgrade-factory-uups.ts
examples/upgradable-example/scripts/upgrade-factory.ts
packages/hardhat-zksync-upgradable/src/constants.ts
packages/hardhat-zksync-upgradable/src/proxy-deployment/deploy-beacon.ts
packages/hardhat-zksync-upgradable/src/proxy-deployment/deploy-impl.ts
packages/hardhat-zksync-upgradable/src/proxy-deployment/deploy-proxy.ts
packages/hardhat-zksync-upgradable/src/proxy-upgrade/upgrade-beacon.ts
packages/hardhat-zksync-upgradable/src/proxy-upgrade/upgrade-proxy.ts
packages/hardhat-zksync-upgradable/src/utils/options.ts
packages/hardhat-zksync-upgradable/src/utils/utils-general.ts

Add factory deps for implementation deployment
In a proxy implementation, a factory might rely on certain dependencies. If these dependencies aren't properly provided or transmitted, transactions might fail, which happen with code "The code hash is not known" returned from ContractDeployer.

fix: add factory deps for implementation deployment

---

.github/workflows/github-release.yml

* Send notifications after github release is created
* So code owners are aware that new package release is present

chore: send notifications after github release is created

---

examples/upgradable-example/hardhat.config.ts
examples/upgradable-example/scripts/deploy-box-beacon.ts
examples/upgradable-example/scripts/deploy-box-proxy.ts
examples/upgradable-example/scripts/deploy-box-uups.ts
examples/upgradable-example/scripts/upgrade-box-beacon.ts
examples/upgradable-example/scripts/upgrade-box-uups.ts
examples/upgradable-example/scripts/upgrade-box.ts

Added smart contract verification to upgradable examples
To ensure the proper operation of the hardhat-zksync-upgradable plugin in combination with hardhat-zksync-verify on zkSync Sepolia Testnet.

fix: add smart contract verification to upgradable examples

---

packages/hardhat-zksync-chai-matchers/src/constants.ts
packages/hardhat-zksync-chai-matchers/src/errors.ts
packages/hardhat-zksync-chai-matchers/src/internal/changeEtherBalance.ts
packages/hardhat-zksync-chai-matchers/src/internal/changeEtherBalances.ts
packages/hardhat-zksync-chai-matchers/src/internal/changeTokenBalance.ts
packages/hardhat-zksync-chai-matchers/src/internal/hardhatChaiMatchers.ts
packages/hardhat-zksync-chai-matchers/src/internal/reverted/reverted.ts
packages/hardhat-zksync-chai-matchers/src/internal/reverted/revertedWith.ts
packages/hardhat-zksync-chai-matchers/src/internal/reverted/revertedWithCustomError.ts
packages/hardhat-zksync-chai-matchers/src/internal/reverted/revertedWithPanic.ts
packages/hardhat-zksync-chai-matchers/src/internal/reverted/revertedWithoutReason.ts
packages/hardhat-zksync-chai-matchers/src/internal/reverted/utils.ts
packages/hardhat-zksync-chai-matchers/src/internal/utils.ts
packages/hardhat-zksync-chai-matchers/test/changeEtherBalance.ts
packages/hardhat-zksync-chai-matchers/test/changeEtherBalances.ts
packages/hardhat-zksync-chai-matchers/test/changeTokenBalance.ts
packages/hardhat-zksync-chai-matchers/test/helpers.ts
packages/hardhat-zksync-chai-matchers/test/types.ts

What 💻
Add support for regex and forbid async matchers from being chained.
Why ✋
In order to extend testing capabilities of the plugin and prevent false positive tests by forbidding chaining matchers that should not be chained.

fix: add support for regex and forbid unsupported chaining

---

packages/hardhat-zksync-solc/src/compile/binary.ts
packages/hardhat-zksync-solc/src/compile/downloader.ts
packages/hardhat-zksync-solc/src/constants.ts
packages/hardhat-zksync-solc/src/index.ts
packages/hardhat-zksync-solc/test/tests/compile/downloader.test.ts

* Set zksolc compiler version for specified compiler path
* Handle real zksolc compilers versions when we download  them from remote origins or if we provide a path to our local path.

fix: set zksolc compiler version for specified compiler path

---

packages/hardhat-zksync-vyper/src/artifacts.ts
packages/hardhat-zksync-vyper/src/index.ts
packages/hardhat-zksync-vyper/test/fixture-projects/factory-with-older-compiler/contracts/CreateForwarder.vy
packages/hardhat-zksync-vyper/test/fixture-projects/factory-with-older-compiler/contracts/DeployMe.vy
packages/hardhat-zksync-vyper/test/fixture-projects/factory-with-older-compiler/hardhat.config.ts
packages/hardhat-zksync-vyper/test/tests.ts

* Support new naming for proxy at forwarder contracts
* With new zkvyper compiler version 1.4.0 proxy contract name is changed.

fix: support new naming for proxy at forwarder contracts

---

packages/hardhat-zksync-solc/src/constants.ts

* Adjust solc message for missing libraries
* hardhat-zksync-deploy handles deployment with integrated accounts, so the message needs to be changed accordingly

fix: adjust solc message for missing libraries

---

packages/hardhat-zksync-solc/src/compile/downloader.ts
packages/hardhat-zksync-solc/test/tests/compile/downloader.test.ts

* Add mock extension for compiler path remote origins
* Windows cannot run binary files without a extension so we need set some mock extension.

fix: add mock extension for compiler path remote origins

---

packages/hardhat-zksync-vyper/src/compile/downloader.ts
packages/hardhat-zksync-vyper/src/constants.ts
packages/hardhat-zksync-vyper/src/index.ts
packages/hardhat-zksync-vyper/src/utils.ts

* Set zkvyper compiler version for specified compiler path
* Handle real zkvyper compilers versions when we download them from remote origins or if we provide a path to our local path.

fix: set zkvyper compiler version for specified compiler path

---

packages/hardhat-zksync-verify/src/plugin.ts
packages/hardhat-zksync-verify/src/task-actions.ts
packages/hardhat-zksync-verify/test/tests/plugin.test.ts

* Send to verify service compiler input settings
* Before implementing these changes, it's BE has received settings from zksolc. However, the introduction of the `evmVersion` field by Hardhat affects how our contracts are compiled. Notably, this change doesn't impact the verification process due to the lack of support for this field in older versions of the zksolc compiler (<1.4.0). Although zksolc compiler 1.4.0 incorporates this field into the compilation process, and now is absent from the verification request.

fix: send to verify service compiler input settings

---

.gitignore
examples/deploy-example/deploy/003_deploy.ts
packages/hardhat-zksync-deploy/package.json
packages/hardhat-zksync-deploy/src/deployer-extension.ts
packages/hardhat-zksync-deploy/src/deployer-helper.ts
packages/hardhat-zksync-deploy/src/deployer.ts
packages/hardhat-zksync-deploy/src/deployment-saver.ts
packages/hardhat-zksync-deploy/src/script-manager.ts
packages/hardhat-zksync-deploy/src/utils.ts
packages/hardhat-zksync-deploy/test/tests/deployment-saver.test.ts
packages/hardhat-zksync-deploy/test/tests/tests.ts
packages/hardhat-zksync-verify/test/tests/plugin.test.ts

*  Update deploy cache logic with script load path support for windows
* Update cache logic to support different constructorArgs, salt, deployment type and to return proper contract.

fix: update deploy cache logic with script load path support for windows

---

packages/hardhat-zksync-deploy/src/index.ts

* Set forceDeploy to true as a default value
* To address unexpected behavior where contracts are being deployed multiple times where forceDeploy being set to false by default, we're considering setting forceDeploy to true as the default value. This adjustment aims to align with user expectations and maintain compatibility with previous versions of the system.

fix: set forceDeploy to true as a default value

---

packages/hardhat-zksync-upgradable/src/index.ts

* Remove hardhat-zksync-deploy import from index.ts
* The import of 'hardhat-zksync-deploy' inside index.ts is unnecessary since 'hardhat-zksync-upgradable' does not override its tasks or environment configurations.

fix: remove hardhat-zksync-deploy import from index.ts

---

packages/hardhat-zksync-verify-vyper/package.json
packages/hardhat-zksync-verify-vyper/src/task-actions.ts
packages/hardhat-zksync-verify-vyper/src/utils.ts

Removed unnecessary dependency from the package.
The dependency is unnecessary, and its removal can reduce maintenance costs.

fix: remove zksync-ethers dependency

---

.github/release-please/config.json
.github/release-please/manifest.json

* pre-release support for hardhat-zksync-verify-vyper
* To automatically support pre-release versions for hardhat-zksync-verify-vyper

chore: pre-release support for hardhat-zksync-verify-vyper

---

packages/hardhat-zksync-upgradable/package.json

* Use hardhat with caret to use single version of hardhat
* The addition of the new hardhat dependency to the project has resulted in Hardhat being unable to extend its environment.

fix: use hardhat with caret to use single version of hardhat

---

examples/basic-example/contracts/003_account_abstraction/TwoUserMultisig.sol
examples/upgradable-example/README.md
examples/verify-example/test/tests.ts
examples/verify-vyper-example/test/tests.ts
packages/hardhat-zksync-chai-matchers/test/fixture-projects/hardhat-project/contracts/TwoUserMultisig.sol
packages/hardhat-zksync-deploy/README.md
packages/hardhat-zksync-deploy/src/utils.ts
packages/hardhat-zksync-verify-vyper/test/tests.ts

1. Fix `examples/basic-example/contracts/003_account_abstraction/TwoUserMultisig.sol`   typo
2. Fix `examples/upgradable-example/README.md`   typo
3. Fix `examples/verify-example/test/tests.ts`   typo
4. Fix `examples/verify-vyper-example/test/tests.ts`   typo
5. Fix `packages/hardhat-zksync-chai-matchers/test/fixture-projects/hardhat-project/contracts/TwoUserMultisig.sol`   typo
6. Fix `packages/hardhat-zksync-deploy/README.md`   typo
7. Fix `packages/hardhat-zksync-deploy/src/utils.ts`   typo
8. Fix `packages/hardhat-zksync-verify-vyper/test/tests.ts`   typo

chore: fix typos

---

packages/hardhat-zksync-node/src/utils.ts
packages/hardhat-zksync-node/test/tests.ts

Properly construct fork arguments when running node.
In order to make forking of the supported chains at specific block.

fix: properly construct fork arguments

---

packages/hardhat-zksync-deploy/README.md
packages/hardhat-zksync-upgradable/README.md
packages/hardhat-zksync-upgradable/src/index.ts
packages/hardhat-zksync-upgradable/src/interfaces.ts
packages/hardhat-zksync-upgradable/src/plugin.ts
packages/hardhat-zksync-upgradable/src/task-actions.ts
packages/hardhat-zksync-upgradable/src/task-names.ts
packages/hardhat-zksync-upgradable/src/utils.ts
packages/hardhat-zksync-upgradable/test/fixture-projects/beacon-e2e/hardhat.config.ts
packages/hardhat-zksync-upgradable/test/fixture-projects/tup-e2e/hardhat.config.ts
packages/hardhat-zksync-upgradable/test/fixture-projects/uups-e2e/hardhat.config.ts
packages/hardhat-zksync-upgradable/test/tests.ts
packages/hardhat-zksync/README.md
packages/hardhat-zksync/src/index.ts
packages/hardhat-zksync/src/plugin.ts
packages/hardhat-zksync/src/task-action.ts
packages/hardhat-zksync/test/tests.ts

* Introducing a new upgradable tasks to run via ci command
* Provided CLI commands enable contract deployment and upgrading, not all arguments may be available (e.g. initializer or kind propery). If these commands lack the required functionality, it may be necessary to utilize scripting for a more comprehensive approach.

feat: introducing a new upgradable tasks to run via ci command

---

packages/hardhat-zksync-upgradable/src/utils/utils-general.ts

* Set valid fromBlock filter to check creation tx hash from the logs
* With the new version of zksync-ethers v5, specifying fromBlock as 0 is no longer valid, and filtering doesn't have the desired effect. To address this, we need to set the fromBlock filter to 'earliest' to effectively search for the creation transaction hash.

fix: set valid fromBlock filter to check creation tx hash from the logs

---

packages/hardhat-zksync-upgradable/README.md
packages/hardhat-zksync-upgradable/src/index.ts
packages/hardhat-zksync-upgradable/src/plugin.ts
packages/hardhat-zksync-upgradable/src/proxy-deployment/deploy-beacon-proxy.ts
packages/hardhat-zksync-upgradable/src/proxy-deployment/deploy-impl.ts
packages/hardhat-zksync-upgradable/src/proxy-deployment/deploy-proxy.ts
packages/hardhat-zksync-upgradable/src/utils/options.ts

* Extend deploy and upgrade of proxy with deployment type and salt
* To support different deployment types and salts.

fix: extend deploy and upgrade of proxy with deployment type and salt for ethers-v5

---

packages/hardhat-zksync-verify/src/constants.ts
packages/hardhat-zksync-verify/src/plugin.ts
packages/hardhat-zksync-verify/src/task-actions.ts
packages/hardhat-zksync-verify/src/utils.ts
packages/hardhat-zksync-verify/test/tests/task-actions.test.ts

* Get valid minimal context for verification BE request
* Verification fallback with exponential backoff.
* To send a proper dependent contracts to the verification BE and to provide proper backoff function if whole context is needed.

fix: get valid minimal context for verification BE request

---

examples/basic-example/deploy/001_deploy.js
examples/basic-example/deploy/002_factory.ts
examples/basic-example/deploy/003_account_abstraction.ts
examples/deploy-example/deploy-zkSync/000_deploy.ts
examples/deploy-example/deploy-zkSync/001_deploy.js
examples/node-example/deploy/001_deploy.js
examples/vyper-example/deploy/deploy.ts
packages/hardhat-zksync-chai-matchers/test/reverted/reverted.ts
packages/hardhat-zksync-deploy/README.md
packages/hardhat-zksync-deploy/src/deployer-extension.ts
packages/hardhat-zksync-deploy/src/deployer.ts
packages/hardhat-zksync-deploy/src/index.ts
packages/hardhat-zksync-deploy/src/plugin.ts
packages/hardhat-zksync-deploy/test/tests/plugin.test.ts

* Set deployment type per each deployment and not per per deployer object
* User can change deployment type per each deployment and don't need to set new deployment type in deployer object or create a new deployer to use a new deployment type.

feat: use deployment type in the deploy function

---

package.json
pnpm-lock.yaml

This PR specifies the package manager to use and its version `v9.2.0` which is latest.
It helps for reproducibility to make sure users use the same version of package manager.
Also some users (like me) uses [corepack](https://nodejs.org/api/corepack.html) to manage my environments between projects.
The lockfile should be updated by running `pnpm install`. Feel free to do it on your side as it will do a lot of changes and I don't know what are your security practices.

chore: specify package manager

---

examples/basic-example/hardhat.config.ts
examples/basic-example/package.json
examples/deploy-example/package.json
examples/mixed-example/package.json
examples/node-example/hardhat.config.ts
examples/node-example/package.json
examples/noninline-libraries-example/package.json
examples/upgradable-example/package.json
examples/verify-example/hardhat.config.ts
examples/verify-example/package.json
packages/hardhat-zksync-chai-matchers/package.json
packages/hardhat-zksync-deploy/package.json
packages/hardhat-zksync-deploy/test/fixture-projects/plugin-functionalities/hardhat.config.ts
packages/hardhat-zksync-node/package.json
packages/hardhat-zksync-upgradable/package.json
packages/hardhat-zksync-verify/package.json
packages/hardhat-zksync-verify/src/config-normalizer.ts
packages/hardhat-zksync-verify/src/plugin.ts
packages/hardhat-zksync-verify/src/task-actions.ts
packages/hardhat-zksync-verify/src/utils.ts
packages/hardhat-zksync-verify/test/tests/config-normalizer.test.ts
packages/hardhat-zksync-verify/test/tests/plugin.test.ts
packages/hardhat-zksync-verify/test/tests/task-actions.test.ts
packages/hardhat-zksync/package.json
pnpm-lock.yaml

* Switches to the default codegen with the zksolc for ethers v5
* These changes with new version 1.5.0 of zksolc will affect a plugin where arguments will be sent from standard json input.

feat: switch to the default codegen with zksync solc

---

packages/hardhat-zksync-upgradable/src/constants.ts
packages/hardhat-zksync-upgradable/src/gas-estimation/estimate-gas-beacon.ts
packages/hardhat-zksync-upgradable/src/gas-estimation/estimate-gas-proxy.ts

* estimateGas support for custom chains
* Due to the hardcoded contracts for supported chains, users are unable to estimate gas for proxies in the current implementation.

fix: estimateGas support for custom chains

---

.github/workflows/ci.yml
examples/download-with-compiler-origin/.eslintrc.js
examples/download-with-compiler-origin/.gitignore
examples/download-with-compiler-origin/README.md
examples/download-with-compiler-origin/contracts/Constant.sol
examples/download-with-compiler-origin/contracts/Foo.sol
examples/download-with-compiler-origin/contracts/Greeter.sol
examples/download-with-compiler-origin/deploy/003_deploy.ts
examples/download-with-compiler-origin/hardhat.config.ts
examples/download-with-compiler-origin/package.json
examples/download-with-compiler-origin/tsconfig.json
packages/hardhat-zksync-solc/src/constants.ts
packages/hardhat-zksync-solc/src/index.ts
packages/hardhat-zksync-solc/src/utils.ts
packages/hardhat-zksync-solc/test/tests/config-update.test.ts
packages/hardhat-zksync-solc/test/tests/tests.ts
packages/hardhat-zksync-solc/test/tests/utils.test.ts
packages/hardhat-zksync-verify/src/constants.ts
packages/hardhat-zksync-verify/src/task-actions.ts
packages/hardhat-zksync-verify/test/tests/task-actions.test.ts
pnpm-lock.yaml

* Compiler path issue with compiler breakable changes
* With the new compiler, the compiler version is needed before the compilation process, requiring the compiler to be downloaded first. This ensures that the plugin can update all settings properly based on the new compiler. Additionally, downloading the compiler from a remote or origin source needs to be addressed with this change.

fix: compiler path issue with compiler breakable changes

---

packages/hardhat-zksync-solc/src/constants.ts
packages/hardhat-zksync-solc/src/utils.ts

* add gnu toolchain for linux as default from compiler version 1.5.3
* ML compiler team managed to make static builds for Linux without musl by linking static glibc. This executable has much better performance, as musl memory manager is much slower.

fix: add gnu toolchain for linux as default from compiler version 1.5.3

---

packages/hardhat-zksync-vyper/src/constants.ts
packages/hardhat-zksync-vyper/src/utils.ts

* add gnu toolchain for linux as default from compiler version 1.5.3
* ML compiler team managed to make static builds for Linux without musl by linking static glibc. This executable has much better performance, as musl memory manager is much slower.

fix: add gnu toolchain for linux as default from compiler version 1.5.4

---

packages/hardhat-zksync-solc/README.md
packages/hardhat-zksync-solc/src/index.ts
packages/hardhat-zksync-solc/src/type-extensions.ts
packages/hardhat-zksync-solc/src/types.ts
packages/hardhat-zksync-solc/test/fixture-projects/suppresed-warnings-errors/contracts/Greeter.sol
packages/hardhat-zksync-solc/test/fixture-projects/suppresed-warnings-errors/hardhat.config.ts
packages/hardhat-zksync-solc/test/tests/tests.ts

* Add suppressed errors and warnings
* zksolc doesn’t suppress those kinds of errors and warnings by default, so users need to configure them in the Hardhat configuration file

fix: add suppressed errors and warnings

---

packages/hardhat-zksync-vyper/src/constants.ts
packages/hardhat-zksync-vyper/src/index.ts
pnpm-lock.yaml

* Download zkvyper if needed before compilation
* It will make the compilation process similar to solc and help the verification plugin resolve the correct zkvyper version.

fix: download zkvyper if needed before compilation

---

e2e/fixture-projects/node/test.sh
packages/hardhat-zksync-ethers/test/tests.ts

* Tests fix for new era test node dynamic fee calculation

chore: test fix for new era test node dynamic fee calculation

---

.github/workflows/ci.yml
README.md
e2e/fixture-projects/node/preprocess.sh
e2e/fixture-projects/node/test.sh
examples/deploy-example/deploy-ZKsync/002_deploy.ts
examples/node-example/README.md
packages/hardhat-zksync-node/README.md
packages/hardhat-zksync-node/package.json
packages/hardhat-zksync-node/src/constants.ts
packages/hardhat-zksync-node/src/downloader.ts
packages/hardhat-zksync-node/src/index.ts
packages/hardhat-zksync-node/src/utils.ts
packages/hardhat-zksync-node/test/tests.ts
packages/hardhat-zksync-upgradable/src/core/provider.ts
packages/hardhat-zksync/README.md
pnpm-lock.yaml

* Updates to make use of anvil-zksync
* era-test-node renamed to anvil-zksync

fix: update naming from era_test_node to anvil-zksync

---

packages/hardhat-zksync-node/src/core/global-interceptor.ts
packages/hardhat-zksync-node/src/core/script-runner.ts
packages/hardhat-zksync-node/src/index.ts
packages/hardhat-zksync-node/src/server.ts
packages/hardhat-zksync-node/src/types.ts
packages/hardhat-zksync-node/src/utils.ts
packages/hardhat-zksync-node/test/tests.ts

- Added flags to show only console.log from contracts when running tests or scripts with zksync hardhat node
- It is useful to see the console.log in the same process, this is how hardhat node also works.

feat: show contract logs while running tests and scripts with zksync hardhat node [DO NOT MERGE]

---

e2e/fixture-projects/compatability-check/hardhat.config.ts
e2e/fixture-projects/compatability-check/preprocess.sh
e2e/fixture-projects/mixed/preprocess.sh
e2e/fixture-projects/node/test.sh
e2e/fixture-projects/upgradeable/preprocess.sh
examples/vyper-example/hardhat.config.ts
packages/hardhat-zksync-verify/src/solc/bytecode.ts
packages/hardhat-zksync-verify/src/solc/metadata.ts
packages/hardhat-zksync-verify/src/task-actions.ts
packages/hardhat-zksync-verify/test/tests/task-actions.test.ts

fixes #1666
1. Fix passing `--contract` argument (looks like the argument name was changed)
2. Fix processing of [keccak metadata](https://matter-labs.github.io/era-compiler-solidity/latest/02-command-line-interface.html#--metadata-hash)

fix: support partial match verification for contracts with keccak metadata

---

packages/hardhat-zksync-solc/src/compile/downloader.ts
packages/hardhat-zksync-solc/src/constants.ts
packages/hardhat-zksync-solc/src/utils.ts
packages/hardhat-zksync-vyper/src/compile/downloader.ts
packages/hardhat-zksync-vyper/src/constants.ts
packages/hardhat-zksync-vyper/src/utils.ts

Add warnings for deprecate versions for security reasons.
Remove usage of old versions of the compilers.
fixes: https://github.com/matter-labs/hardhat-zksync/issues/1732, https://github.com/matter-labs/hardhat-zksync/issues/1733

fix: add warnings for deprecated versions

---

packages/hardhat-zksync-node/src/constants.ts

* anvil-zksync bump default version

fix: anvil-zksync bump default version

---

packages/hardhat-zksync-node/src/index.ts
packages/hardhat-zksync-node/src/types.ts
packages/hardhat-zksync-node/src/utils.ts
packages/hardhat-zksync-node/test/tests.ts

* To avoid a collision with the --silent parameter in hardhat-deploy node task, the parameter was renamed to --quiet.

fix: rename silent param to quiet

---

packages/hardhat-zksync-solc/src/compile/downloader.ts
packages/hardhat-zksync-solc/src/compile/zkvm-solc-downloader.ts
packages/hardhat-zksync-solc/src/utils.ts
packages/hardhat-zksync-solc/test/tests/utils.test.ts

Removes the old zksolc-bin-like URL format.
It caused unexpected falling back to the old URL in some environments for some reason.

fix: remove the old URL format
